readyapi:
    build:
      context: .
      dockerfile: readyapi/Dockerfile.readyapi
    depends_on: [kafka, mysql, mockserver]
    environment:
    
      KAFKA_BOOTSTRAP: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: social_security
      MYSQL_USER: qa_user
      MYSQL_PASS: qa_pass
      API_BASE_URL: http://mockserver:1080

    
      # READYAPI_LICENSE_SERVER: "27000@license-server"
      # READYAPI_LICENSE_KEY: "xxxxx"
    volumes:
      - ./artifacts:/work/artifacts
    command: >
      /opt/readyapi/bin/testrunner.sh
      -s "YourTestSuiteName"
      -c "YourTestCaseName"
      -r
      -j
      -f /work/artifacts
      /work/readyapi/ReadyAPIIntegration.xml
